[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.10
  adafruit/Adafruit SSD1306 @ ^2.5.11
  adafruit/Adafruit SH110X @ ^2.1.12
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  +<main.cpp>
  -<test_oled_soil.cpp>

[env:oled-soil-test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.10
  adafruit/Adafruit SSD1306 @ ^2.5.11
  adafruit/Adafruit SH110X @ ^2.1.12
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  +<test_oled_soil.cpp>
  -<main.cpp>
